version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $DOCKER_DB_PASSWORD
      POSTGRES_USER: $DOCKER_DB_USER
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
